import { randomBytes, randomInt, randomUUID } from 'crypto';
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { createServerSupabaseClient } from '@/lib/supabase-server';

export const runtime = 'nodejs';

interface CreatePartnerRequest {
  full_name: string;
  email: string;
  password?: string;
  business_name: string;
  business_description?: string;
  contact_email?: string;
  website_url?: string;
  is_active?: boolean;
}

function isValidEmail(value: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function generatePassword(length = 14): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';
  let output = '';
  for (let i = 0; i < length; i += 1) {
    output += chars[randomInt(0, chars.length)];
  }
  return output;
}

function createServiceRoleClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error('Missing server Supabase configuration.');
  }

  return createClient(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });
}

async function logAdminAction(
  adminClient: ReturnType<typeof createServiceRoleClient>,
  actorId: string,
  action: string,
  details: Record<string, unknown>
) {
  const { error } = await adminClient.from('admin_action_logs').insert({
    actor_id: actorId,
    action,
    details,
  });

  if (error) {
    console.warn('Failed to write admin action log:', error.message);
  }
}

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

export async function POST(request: Request) {
  try {
    const supabase = await createServerSupabaseClient();
    const {
      data: { user: actor },
      error: actorError,
    } = await supabase.auth.getUser();

    if (actorError || !actor) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { data: actorProfile, error: actorProfileError } = await supabase
      .from('users')
      .select('role')
      .eq('id', actor.id)
      .maybeSingle();

    if (actorProfileError) {
      return NextResponse.json({ error: actorProfileError.message }, { status: 500 });
    }

    if (!actorProfile || actorProfile.role !== 'admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = (await request.json()) as Partial<CreatePartnerRequest>;
    const fullName = (body.full_name || '').trim();
    const email = (body.email || '').trim().toLowerCase();
    const businessName = (body.business_name || '').trim();
    const contactEmail = (body.contact_email || '').trim().toLowerCase();
    const businessDescription = (body.business_description || '').trim();
    const websiteUrl = (body.website_url || '').trim();
    const isActive = body.is_active ?? true;

    if (!fullName || !email || !businessName) {
      return NextResponse.json(
        { error: 'full_name, email and business_name are required.' },
        { status: 400 }
      );
    }

    if (!isValidEmail(email)) {
      return NextResponse.json({ error: 'Invalid email format.' }, { status: 400 });
    }

    if (contactEmail && !isValidEmail(contactEmail)) {
      return NextResponse.json({ error: 'Invalid contact email format.' }, { status: 400 });
    }

    if (websiteUrl) {
      try {
        // Validate URL shape before inserting.
        // eslint-disable-next-line no-new
        new URL(websiteUrl);
      } catch {
        return NextResponse.json({ error: 'Invalid website URL.' }, { status: 400 });
      }
    }

    const autoGeneratedPassword = !body.password || body.password.trim().length === 0;
    const password = autoGeneratedPassword ? generatePassword() : body.password!.trim();

    if (password.length < 8) {
      return NextResponse.json(
        { error: 'Password must be at least 8 characters long.' },
        { status: 400 }
      );
    }

    const adminClient = createServiceRoleClient();
    let createdUserId: string | null = null;
    let createdAuthUser = false;
    let partnerSaved = false;

    const { data: existingUserRow, error: existingUserError } = await adminClient
      .from('users')
      .select('id')
      .eq('email', email)
      .maybeSingle();

    if (existingUserError) {
      return NextResponse.json({ error: existingUserError.message }, { status: 500 });
    }

    try {
      if (existingUserRow?.id) {
        createdUserId = existingUserRow.id;
      } else {
        const { data: authCreated, error: authCreateError } = await adminClient.auth.admin.createUser({
          email,
          password,
          email_confirm: true,
          user_metadata: { full_name: fullName },
        });

        if (authCreateError) {
          const msg = authCreateError.message.toLowerCase();
          if (msg.includes('already') || msg.includes('registered') || msg.includes('exists')) {
            return NextResponse.json(
              { error: 'A user with this email already exists. Use this same form to attach business profile data.' },
              { status: 409 }
            );
          }
          return NextResponse.json({ error: authCreateError.message }, { status: 400 });
        }

        createdUserId = authCreated.user?.id || null;
        createdAuthUser = true;
      }

      if (!createdUserId) {
        return NextResponse.json({ error: 'Auth user creation returned no user id.' }, { status: 500 });
      }

      // Trigger on auth.users should create public.users; wait briefly before fallback insert.
      let hasUserRow = false;
      for (let i = 0; i < 5; i += 1) {
        const { data: maybeUser } = await adminClient
          .from('users')
          .select('id')
          .eq('id', createdUserId)
          .maybeSingle();

        if (maybeUser?.id) {
          hasUserRow = true;
          break;
        }
        await sleep(200);
      }

      if (!hasUserRow) {
        const fallbackQrSecret = randomBytes(16).toString('hex');
        const { error: userInsertError } = await adminClient.from('users').insert({
          id: createdUserId,
          email,
          full_name: fullName,
          qr_code_secret: fallbackQrSecret,
          role: 'partner',
        });

        if (userInsertError) {
          return NextResponse.json({ error: userInsertError.message }, { status: 500 });
        }
      }

      const { error: userUpdateError } = await adminClient
        .from('users')
        .update({ full_name: fullName, email, role: 'partner' })
        .eq('id', createdUserId);

      if (userUpdateError) {
        return NextResponse.json({ error: userUpdateError.message }, { status: 500 });
      }

      const { data: existingPartner, error: existingPartnerError } = await adminClient
        .from('partners')
        .select('id')
        .eq('user_id', createdUserId)
        .maybeSingle();

      if (existingPartnerError) {
        return NextResponse.json({ error: existingPartnerError.message }, { status: 500 });
      }

      const partnerPayload = {
        user_id: createdUserId,
        business_name: businessName,
        business_description: businessDescription || null,
        contact_email: contactEmail || email,
        website_url: websiteUrl || null,
        is_active: isActive,
        updated_at: new Date().toISOString(),
      };

      if (existingPartner?.id) {
        const { error: partnerUpdateError } = await adminClient
          .from('partners')
          .update(partnerPayload)
          .eq('id', existingPartner.id);

        if (partnerUpdateError) {
          return NextResponse.json({ error: partnerUpdateError.message }, { status: 500 });
        }
      } else {
        const { error: partnerInsertError } = await adminClient
          .from('partners')
          .insert({ id: randomUUID(), ...partnerPayload });

        if (partnerInsertError) {
          return NextResponse.json({ error: partnerInsertError.message }, { status: 500 });
        }
      }

      partnerSaved = true;

      await logAdminAction(
        adminClient,
        actor.id,
        'partner.created_or_updated',
        {
          user_id: createdUserId,
          email,
          business_name: businessName,
          existing_user: !createdAuthUser,
          auto_generated_password: createdAuthUser && autoGeneratedPassword,
        }
      );

      return NextResponse.json(
        {
          success: true,
          user_id: createdUserId,
          email,
          temporary_password: createdAuthUser && autoGeneratedPassword ? password : null,
          existing_user: !createdAuthUser,
        },
        { status: 201 }
      );
    } finally {
      // Best-effort rollback to avoid orphan auth accounts on partial failures.
      if (createdAuthUser && createdUserId && !partnerSaved) {
        await adminClient.auth.admin.deleteUser(createdUserId);
      }
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unexpected error creating partner.';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
